### ISSUE TITLE
"Gas" type not included in ServiceType

### ISSUE THREAD

**Issue by coreyauger** [Genability/genability-java#53]
Type of service for the tariff. Current values include ELECTRICITY (grid power), SOLAR_PV (for a Solar PPA, Lease or similar) and GAS (Natural Gas)
--

Also noticed there are no types for `TariffHistory`
I am happy to submit a PR if this is something that is still actively worked on?

**Comment by mgerring** [comment]
Fixed in https://github.com/Genability/genability-java/commit/11f0f6c324e3a6598953805a26a00c7840cc6a6f
