### ISSUE TITLE
CalculatedCostItem has a rateType, while a TariffRateBand has a rateUnit

### ISSUE THREAD

**Issue by ryantenney** [Genability/genability-java#8]
Is this intended?

CalculatedCostItem:
https://github.com/Genability/genability-java/blob/ff1110110975e22218715984ff1f13781345c3e7/src/main/java/com/genability/client/types/CalculatedCostItem.java#L25

TariffRateBand:
https://github.com/Genability/genability-java/blob/ff1110110975e22218715984ff1f13781345c3e7/src/main/java/com/genability/client/types/TariffRateBand.java#L22

**Comment by sharris-genability** [comment]
(2 years later) Yes. These names match the fields available in the API. Sorry for the delayed response!

**Comment by sharris-genability** [comment]
See [here](http://developer.genability.com/documentation/api-reference/tariff-api/tariff/#tariff-rate-band) and [here](http://developer.genability.com/documentation/api-reference/account-api/cost-calculator/#calculated-cost-item) for TariffRateBand and CalculatedCostItem, respectively.
